site_name: Single Molecule Tracking
# site_url: TO-DO
# repo_url: TO-DO
# repo_name: TO-DO
copyright: Copyright &copy; 2025, Friedrich Miescher Institute for Biomedical Research
nav:
  - Home: index.md
  - Data: data.md
  - Installation: installation.md
  - Tutorial:
    - 'Tutorials': tutorial/tutorials.md
  - 'How-to Guide':
    - 'Guides': how_to/guides.md
    - 'N2V':
        - 'Generate Training Data': how_to/N2V_generate_train_data.md
        - 'Train': how_to/N2V_train_model.md
        - 'Predict': how_to/N2V_predict.md
    - 'Mask creation and preprocessing':
        - 'Mask creation': how_to/Mask-creation.md
        - 'Preprocessing': how_to/Preprocessing.md
    - 'Spot detection': how_to/Spot-detection.md
    - 'Tracking': how_to/Tracking.md
    - 'Visualization': how_to/Visualization.md
    - 'Feature extraction': how_to/Feature-extraction.md
  - Explanation:
    - 'Explanations': explanation/explanations.md
  - References:
    - References: references/references.md
  - Imprint: imprint.md
theme:
  name: material
  favicon: images/favicon.ico
  icon:
    repo:
      fontawesome/brands/github
  font:
    text: Source Sans Pro
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - header.autohide
    - content.code.copy
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
plugins:
  - offline:
      enabled: !ENV [ OFFLINE, false ]  # noqa
#  - git-revision-date-localized:
#      enable_creation_date: true
#   - git-committers:
#       repository: TO-DO
#       branch: main
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
