[project]
name = "Single Molecule Tracking"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tim-Oliver Buchholz <tim-oliver.buchholz@fmi.ch>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[system-requirements]
# Minimum linux version for this project to work.
# This is necessary of some HPC setups, which run on e.g. Rocky Linux 8.
linux="4.18"

[tasks]
source_status = { cmd = 'echo "Found $(git status --porcelain ipa | wc -l) untracked changes in ./ipa." && exit $(git status --porcelain ipa | wc -l)'}
log_commit = {cmd = 'echo "[$(date -Iseconds)][Executing] $TASK [Git-Commit] $(git rev-parse --verify HEAD)" >> $WD/githash.log', env = {TASK = ""}}
build_config = { cmd = "mkdir -p $WD ; TASK=BUILD_CONFIG pixi run log_commit ; cd $WD ; pixi run python $PIXI_PROJECT_ROOT/ipa/n2v/build_config.py", env = { WD = "runs/example"}, depends_on=["source_status"]}
generate_data = { cmd = "TASK=GENERATE_DATA pixi run log_commit ; cd $WD ; pixi run -e n2v python $PIXI_PROJECT_ROOT/ipa/n2v/generate_train_data_2D.py", env = { WD = "runs/example"}, depends_on=["source_status"]}
train = { cmd = "TASK=TRAIN pixi run log_commit ; cd $WD ; pixi run -e n2v python $PIXI_PROJECT_ROOT/ipa/n2v/train.py", env = { WD = "runs/example"}, depends_on=["source_status"]}
predict = { cmd = "TASK=PREDICT pixi run log_commit ; cd $WD ; pixi run -e n2v python $PIXI_PROJECT_ROOT/ipa/n2v/predict.py", env={WD = "runs/example"}, depends_on=["source_status"]}
submit_job = { cmd = "TASK=SUBMIT_JOB pixi run log_commit ; sbatch ipa/n2v/slurm-job_$JOB.sh $ACCOUNT $WD", env = { JOB = "", ACCOUNT = "", WD = ""}, depends_on=["source_status"]}

[dependencies]
python = ">=3.9,<3.13"
tqdm = ">=4.66.2,<4.67"
tifffile = ">=2024.5.10,<2024.6"
imagecodecs = {version="*", channel="conda-forge"}
libjpeg-turbo = {version="*", channel="conda-forge"}
pyyaml = ">=6.0.1,<6.1"
pydantic = ">=2.7.1,<3.0"
scikit-image = ">=0.22.0,<0.23"
questionary = ">=2.0.1,<2.1"
bokeh = ">=3.4.1,<3.5"
dask-image = ">=2024.5.3,<2024.6"
dask = ">=2024.5.1,<2024.6"
distributed = ">=2024.5.1,<2024.6"
pixi-pycharm = ">=0.0.5,<0.1"

[pypi-dependencies]
faim-ipa = ">=0.3.5,<0.4"

[feature.docs.dependencies]
mkdocs-material = ">=9.5.18,<9.6"
mkdocs-git-committers-plugin-2 = ">=2.3.0,<2.4"
mkdocstrings = ">=0.24.3,<0.25"
mkdocstrings-python = ">=1.9.2,<1.10"
mkdocs = ">=1.5.3,<1.6"
mkdocs-git-revision-date-localized-plugin = ">=1.2.4,<1.3"

[feature.docs.tasks]
clean_docs = "rm -rf site"
build_docs = { cmd ="OFFLINE=TRUE mkdocs build", depends_on=["clean_docs"] }
show_docs = "mkdocs serve"

[feature.dev.dependencies]
pre-commit = ">=3.1.1,<3.8"

[feature.dev.tasks]
install_hooks = "pre-commit install"
lint = { cmd="pre-commit run --all-files", depends_on=["install_hooks"] }

[feature.nextflow.target.linux-64.dependencies]
nextflow = ">=23.10.1,<23.11"

[feature.jupyter.dependencies]
jupyter = ">=1.0.0,<1.1"

[feature.jupyter.tasks]
jupyter = "jupyter lab"

[feature.nbdev.dependencies]
nbdev = ">=2.2.10,<2.3"

[feature.nbdev.tasks]
clean = "nbdev_clean --clear_all"

[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "11" }
channels = ["conda-forge"]
dependencies = { tensorflow-gpu="*"}

[feature.n2v.pypi-dependencies]
n2v = ">=0.3.2,<0.3.3"

[feature.cellpose]
channels = ["nvidia", "pytorch", "conda-forge"]

[feature.cellpose.dependencies]
python = "==3.11"
numpy = "<2"
scipy = ">=1.10.1,<1.11"
natsort = ">=8.4.0,<8.5"
numba = ">=0.58.1,<0.59"
pyqt = ">=5.15.9,<5.16"

[feature.cellpose.pypi-dependencies]
cellpose = {version=">=3.0.10, <3.1", extras=["gui"]}

[feature.pytorch]
channels = ["pytorch", "conda-forge"]

[feature.pytorch.dependencies]
pytorch = {version=">=2.3.1,<2.4", channel="pytorch"}

[feature.pytorch-gpu]
channels = ["nvidia", "pytorch", "conda-forge"]
system-requirements = { cuda = "11" }

[feature.pytorch-gpu.dependencies]
pytorch-cuda = {version="11.8.*", channel="pytorch"}

[environments]
docs = ["docs"]
dev = ["dev"]
nextflow = ["nextflow"]
jupyter = ["jupyter"]
nbdev = {features=["nbdev"], no-default-feature = true}
n2v = ["n2v", "cuda"]
cellpose = ["cellpose", "pytorch"]
cellpose-gpu = ["cellpose", "pytorch", "pytorch-gpu"]
