[workspace]
name = "Single Molecule Tracking"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tim-Oliver Buchholz <tim-oliver.buchholz@fmi.ch>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[system-requirements]
# Minimum linux version for this project to work.
# This is necessary of some HPC setups, which run on e.g. Rocky Linux 8.
linux="4.18"

[tasks]
source_status = { cmd = 'echo "Found $(git status --porcelain ipa | wc -l) untracked changes in ./ipa." && exit $(git status --porcelain ipa | wc -l)'}
log_commit = {cmd = 'echo "[$(date -Iseconds)][Executing] $TASK [Git-Commit] $(git rev-parse --verify HEAD)" >> $WD/githash.log', env = {TASK = ""}}
build_config = { cmd = "mkdir -p $WD ; TASK=BUILD_CONFIG pixi run log_commit ; cd $WD ; pixi run python $PIXI_PROJECT_ROOT/ipa/00_denoising-with-n2v/build_config.py", env = { WD = "runs/example"}, depends-on=["source_status"]}
generate_data = { cmd = "TASK=GENERATE_DATA pixi run log_commit ; cd $WD ; pixi run -e n2v python $PIXI_PROJECT_ROOT/ipa/00_denoising-with-n2v/generate_train_data_2D.py", env = { WD = "runs/example"}, depends-on=["source_status"]}
train = { cmd = "TASK=TRAIN pixi run log_commit ; cd $WD ; pixi run -e n2v python $PIXI_PROJECT_ROOT/ipa/00_denoising-with-n2v/train.py", env = { WD = "runs/example"}, depends-on=["source_status"]}
predict = { cmd = "TASK=PREDICT pixi run log_commit ; cd $WD ; pixi run -e n2v python $PIXI_PROJECT_ROOT/ipa/00_denoising-with-n2v/predict.py", env={WD = "runs/example"}, depends-on=["source_status"]}
submit_job = { cmd = "TASK=SUBMIT_JOB pixi run log_commit ; sbatch ipa/00_denoising-with-n2v/slurm-job_$JOB.sh $ACCOUNT $WD", env = { JOB = "", ACCOUNT = "", WD = ""}, depends-on=["source_status"]}

[tasks.iNeuron_cell_segmentation_config]
cmd = """
mkdir -p $WD ;
TASK=iNeuron_cell_segmentation_config pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/build_config_cellpose.py
"""
env = { WD="" }
#depends-on=["source_status"]

[tasks.iNeuron_cell_segmentation]
cmd = """
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/cellpose_predict.py --config cellpose_config.yaml
"""
env = { WD=""}
depends-on = [ "iNeuron_cell_segmentation_config" ]

[tasks.spot_detection_config]
cmd = """
mkdir -p $WD ;
TASK=spot_detection_config pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/02_spot-detection/build_config.py
"""
env = { WD="" }
#depends-on=["source_status"]

[tasks.spot_detection]
cmd = """
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/02_spot-detection/run_spot_detection.py --config spot_detection_config.yaml
"""
env = { WD=""}
depends-on = [ "spot_detection_config" ]

[tasks.spot_detection_with_cytoskeleton_config]
cmd = """
mkdir -p $WD ;
TASK=spot_detection_with_cytoskeleton_config pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/02_spot-detection/build_config_with_cytoskeleton.py
"""
env = { WD="" }
#depends-on=["source_status"]

[tasks.spot_detection_with_cytoskeleton]
cmd = """
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/02_spot-detection/run_spot_detection_with_cytoskeleton.py --config spot_detection_config.yaml
"""
env = { WD=""}
depends-on = [ "spot_detection_with_cytoskeleton_config" ]

[tasks.tracking_config]
cmd = """
mkdir -p $WD ;
TASK=tracking_config pixi run log_commit ;
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/03_spot-tracking/build_config.py
"""
env = { WD="" }
#depends-on=["source_status"]

[tasks.tracking]
cmd = """
cd $WD ;
python $PIXI_PROJECT_ROOT/ipa/03_spot-tracking/run_tracking.py --config tracking_config.yaml
"""
env = { WD=""}
depends-on = [ "tracking_config" ]

[dependencies]
python = ">=3.9,<3.10"
tqdm = ">=4.66.2,<4.67"
tifffile = "==2023.2.28"
imagecodecs = {version="*", channel="conda-forge"}
libjpeg-turbo = {version="*", channel="conda-forge"}
pyyaml = ">=6.0.1,<6.1"
pydantic = "==1.10.8"
scikit-image = "==0.20.0"
questionary = ">=2.0.1,<2.1"
bokeh = ">=3.4.1,<3.5"
distributed = "==2023.5.1"
scikit-learn = "==1.3.2"
scipy = "==1.9.1"
seaborn-base = "==0.12.2"
trackpy = "==0.6.1"
numpy = "==1.24.3"
matplotlib = "==3.7.1"
cellpose = "*"

[pypi-dependencies]
faim-ipa = ">=0.3.5,<0.4"

[feature.docs.dependencies]
mkdocs-material = ">=9.5.18,<9.6"
mkdocs-git-committers-plugin-2 = ">=2.3.0,<2.4"
mkdocstrings = ">=0.24.3,<0.25"
mkdocstrings-python = ">=1.9.2,<1.10"
mkdocs = ">=1.5.3,<1.6"
mkdocs-git-revision-date-localized-plugin = ">=1.2.4,<1.3"

[feature.docs.tasks]
clean_docs = "rm -rf site"
build_docs = { cmd ="OFFLINE=TRUE mkdocs build", depends-on=["clean_docs"] }
show_docs = "mkdocs serve"

[feature.dev.dependencies]
pre-commit = ">=3.1.1,<3.8"

[feature.dev.tasks]
install_hooks = "pre-commit install"
lint = { cmd="pre-commit run --all-files", depends-on=["install_hooks"] }

[feature.nextflow.target.linux-64.dependencies]
nextflow = ">=23.10.1,<23.11"

[feature.jupyter.dependencies]
jupyter = ">=1.0.0,<1.1"
napari = "==0.4.17"
pyqt = "==5.15.7"

[feature.jupyter.tasks]
jupyter = "jupyter lab"

[feature.jupyter.tasks.organoid_mask_creation]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/Organoid_mask_creation.ipynb $WD ;
cd $WD ;
jupyter lab Organoid_mask_creation.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.iNeuron_zstack_processing]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/iNeuron_zstack_processing.ipynb $WD ;
cd $WD ;
jupyter lab iNeuron_zstack_processing.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.iNeuron_single_slices]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/iNeuron_single_slices.ipynb $WD ;
cd $WD ;
jupyter lab iNeuron_single_slices.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.iNeuron_mask_creation]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/iNeuron_mask_creation.ipynb $WD ;
cd $WD ;
jupyter lab iNeuron_mask_creation.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.iPSC_mask_creation]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/iPSC_mask_creation.ipynb $WD ;
cd $WD ;
jupyter lab iPSC_mask_creation.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.vascular-progenitors_mask_creation]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/vascular-progenitors_mask_creation.ipynb $WD ;
cd $WD ;
jupyter lab vascular-progenitors_mask_creation.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.merge_raw_denoised_image]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/Merge_raw_denoised_image.ipynb $WD ;
cd $WD ;
jupyter lab Merge_raw_denoised_image.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.file_renaming]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/01_mask-creation-preprocessing/File_renaming.ipynb $WD ;
cd $WD ;
jupyter lab File_renaming.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.visualization]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/04_visualization/Spot-detection-tracking_visualization.ipynb $WD ;
cd $WD ;
jupyter lab Spot-detection-tracking_visualization.ipynb
"""
#env = { WD=""}

[feature.jupyter.tasks.calculate_distance-to-nucleus]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/05_feature-extraction/Calculate_distance_to_nucleus.ipynb $WD ;
cd $WD ;
jupyter lab Calculate_distance_to_nucleus.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.cell_compartments]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/05_feature-extraction/Cell_compartments_nuc_dist.ipynb $WD ;
cd $WD ;
jupyter lab Cell_compartments_nuc_dist.ipynb
"""
env = { WD=""}

[feature.jupyter.tasks.nuc_dist_edge_dist]
cmd = """
cp $PIXI_PROJECT_ROOT/ipa/05_feature-extraction/Nuc_dist_edge_dist.ipynb $WD ;
cd $WD ;
jupyter lab Nuc_dist_edge_dist.ipynb
"""
env = { WD=""}

[feature.nbdev.dependencies]
nbdev = ">=2.2.10,<2.3"

[feature.nbdev.tasks]
clean = "nbdev_clean --clear_all"

[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "11" }
channels = ["conda-forge"]
dependencies = { tensorflow="*"}

[feature.n2v.pypi-dependencies]
n2v = ">=0.3.2,<0.3.3"

[feature.cellpose]
platforms = ["linux-64"]
channels = ["nvidia", "pytorch", "conda-forge"]

[feature.cellpose.dependencies]
python = "==3.11"
numpy = "<2"
scipy = ">=1.10.1,<1.11"
natsort = ">=8.4.0,<8.5"
numba = ">=0.58.1,<0.59"
pyqt = ">=5.15.9,<5.16"

[feature.cellpose.pypi-dependencies]
cellpose = {version=">=3.0.10, <3.1", extras=["gui"]}

[feature.pytorch]
channels = ["pytorch", "conda-forge"]

[feature.pytorch.dependencies]
pytorch = {version=">=2.3.1,<2.4", channel="pytorch"}

[feature.pytorch-gpu]
channels = ["nvidia", "pytorch", "conda-forge"]
system-requirements = { cuda = "11" }

[feature.pytorch-gpu.dependencies]
pytorch-cuda = {version="11.8.*", channel="pytorch"}

[environments]
docs = { features=["docs"], solve-group="default" }
dev = { features=["dev"], solve-group="default" }
nextflow = { features=["nextflow"], solve-group="default" }
jupyter = { features=["jupyter"], solve-group="default" }
n2v = {features=["n2v", "cuda"], solve-group="default" }
nbdev = {features=["nbdev"], no-default-feature = true}
cellpose = {features=["cellpose", "pytorch"], no-default-feature = true}
cellpose-gpu = {features=["cellpose", "pytorch", "pytorch-gpu"], no-default-feature = true}
